### ISSUE TITLE
Android: System.NotSupportedException: Unable to activate instance of type Java.Lang.Thread+RunnableImplementor from native handle

### ISSUE THREAD

**Issue by adrianknight89** [molinch/FFImageLoading#156]
Using this on:

FFImageLoading 2.0.7
Xamarin Forms 2.1.0.6521
Compile using Android 6.0 Marshmallow
Minimum target Android 4.4 (SDK 19)

I have a ListView with ~200 items (embedded png files). When I scroll fast up or down like a child, I get the following error:

```
Unhandled Exception:

System.NotSupportedException: Unable to activate instance of type Java.Lang.Thread+RunnableImplementor from native handle 0xffea90dc (key_handle 0x1f522868).

03-06 05:02:36.471 D/Mono    (10413): DllImport attempting to load: '/system/lib/liblog.so'.
03-06 05:02:36.471 D/Mono    (10413): DllImport loaded library '/system/lib/liblog.so'.
03-06 05:02:36.471 D/Mono    (10413): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
03-06 05:02:36.471 D/Mono    (10413): Searching for '__android_log_print'.
03-06 05:02:36.471 D/Mono    (10413): Probing '__android_log_print'.
03-06 05:02:36.471 D/Mono    (10413): Found as '__android_log_print'.
03-06 05:02:36.491 I/MonoDroid(10413): UNHANDLED EXCEPTION:
03-06 05:02:36.491 I/MonoDroid(10413): System.NotSupportedException: Unable to activate instance of type Java.Lang.Thread+RunnableImplementor from native handle 0xffea90dc (key_handle 0x1f522868). ---> System.MissingMethodException: No constructor found for Java.Lang.Thread+RunnableImplementor::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
03-06 05:02:36.491 I/MonoDroid(10413): Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
03-06 05:02:36.491 I/MonoDroid(10413):   --- End of managed exception stack trace ---
03-06 05:02:36.491 I/MonoDroid(10413): java.lang.Error: Java callstack:
03-06 05:02:36.491 I/MonoDroid(10413): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
03-06 05:02:36.491 I/MonoDroid(10413): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
03-06 05:02:36.501 I/MonoDroid(10413): 	at android.os.Handler.handleCallback(Handler.java:739)
03-06 05:02:36.501 I/MonoDroid(10413): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-06 05:02:36.501 I/MonoDroid(10413): 	at android.os.Looper.loop(Looper.java:145)
03-06 05:02:36.501 I/MonoDroid(10413): 	at android.app.ActivityThread.main(ActivityThread.java:6837)
03-06 05:02:36.501 I/MonoDroid(10413): 	at java.lang.reflect.Method.invoke(Native Method)
03-06 05:02:36.501 I/MonoDroid(10413): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-06 05:02:36.501 I/MonoDroid(10413): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
03-06 05:02:36.501 I/MonoDroid(10413): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
03-06 05:02:36.501 I/MonoDroid(10413):   --- End of inner exception stack trace ---
03-06 05:02:36.501 I/MonoDroid(10413):   at Java.Interop.TypeManager.CreateProxy (System.Type type, IntPtr handle, JniHandleOwnership transfer) [0x00039] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Interop/TypeManager.cs:304 
03-06 05:02:36.501 I/MonoDroid(10413):   at Java.Interop.TypeManager.CreateInstance (IntPtr handle, JniHandleOwnership transfer, System.Type targetType) [0x00138] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Interop/TypeManager.cs:282 
03-06 05:02:36.501 I/MonoDroid(10413):   --- End of inner exception stack trace ---
03-06 05:02:36.501 I/MonoDroid(10413):   at Java.Interop.TypeManager.CreateInstance (IntPtr handle, JniHandleOwnership transfer, System.Type targetType) [0x00186] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Interop/TypeManager.cs:289 
03-06 05:02:36.501 I/MonoDroid(10413):   at Java.Lang.Object.GetObject (IntPtr handle, JniHandleOwnership transfer, System.Type type) [0x000e5] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:459 
03-06 05:02:36.501 I/MonoDroid(10413):   at Java.Lang.Object._GetObject[T] (IntPtr handle, JniHandleOwnership transfer) [0x0001a] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:430 
03-06 05:02:36.501 I/MonoDroid(10413):   at Java.Lang.Object.GetObject[T] (IntPtr handle, JniHandleOwnership transfer) [0x00000] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:422 
03-06 05:02:36.501 I/MonoDroid(10413):   at Java.Lang.Object.GetObject[T] (IntPtr jnienv, IntPtr handle, JniHandleOwnership transfer) [0x00006] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:416 
03-06 05:02:36.501 I/MonoDroid(10413):   at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00000] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:80 
03-06 05:02:36.501 I/MonoDroid(10413):   at (wrapper dynamic-method) System.Object:6c669bbf-ce55-4191-a207-719115cb843c (intptr,intptr)
03-06 05:02:36.541 W/Xamarin.Insights(10413): Warning: Unhandled exception: System.NotSupportedException: Unable to activate instance of type Java.Lang.Thread+RunnableImplementor from native handle 0xffea90dc (key_handle 0x1f522868). ---> System.MissingMethodException: No constructor found for Java.Lang.Thread+RunnableImplementor::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
03-06 05:02:36.541 W/Xamarin.Insights(10413): Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
03-06 05:02:36.541 W/Xamarin.Insights(10413): 
03-06 05:02:36.541 W/Xamarin.Insights(10413):   --- End of managed exception stack trace ---
03-06 05:02:36.541 W/Xamarin.Insights(10413): java.lang.Error: Java callstack:
03-06 05:02:36.541 W/Xamarin.Insights(10413): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
03-06 05:02:36.541 W/Xamarin.Insights(10413): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
03-06 05:02:36.541 W/Xamarin.Insights(10413): 	at android.os.Handler.handleCallback(Handler.java:739)
03-06 05:02:36.541 W/Xamarin.Insights(10413): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-06 05:02:36.541 W/Xamarin.Insights(10413): 	at android.os.Looper.loop(Looper.java:145)
03-06 05:02:36.541 W/Xamarin.Insights(10413): 	at android.app.ActivityThread.main(ActivityThread.java:6837)
03-06 05:02:36.541 W/Xamarin.Insights(10413): 	at java.lang.reflect.Method.invoke(Native Method)
03-06 05:02:36.541 W/Xamarin.Insights(10413): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-06 05:02:36.541 W/Xamarin.Insights(10413): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
03-06 05:02:36.541 W/Xamarin.Insights(10413): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
03-06 05:02:36.541 W/Xamarin.Insights(10413): 
03-06 05:02:36.541 W/Xamarin.Insights(10413):   --- End of inner exception stack trace ---
03-06 05:02:36.541 W/Xamarin.Insights(10413):   at Java.Interop.TypeManager.CreateProxy (System.Type type, IntPtr handle, JniHandleOwnership transfer) [0x00039] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Interop/TypeManager.cs:304 
03-06 05:02:36.541 W/Xamarin.Insights(10413):   at Java.Interop.TypeManager.CreateInstance (IntPtr handle, JniHandleOwnership transfer, System.Type targetType) [0x00138] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Interop/TypeManager.cs:282 
03-06 05:02:36.541 W/Xamarin.Insights(10413):   --- End of inner exception stack trace ---
03-06 05:02:36.541 W/Xamarin.Insights(10413):   at Java.Interop.TypeManager.CreateInstance (IntPtr handle, JniHandleOwnership transfer, System.Type targetType) [0x00186] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Interop/TypeManager.cs:289 
03-06 05:02:36.541 W/Xamarin.Insights(10413):   at Java.Lang.Object.GetObject (IntPtr handle, JniHandleOwnership transfer, System.Type type) [0x000e5] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:459 
03-06 05:02:36.541 W/Xamarin.Insights(10413):   at Java.Lang.Object._GetObject[T] (IntPtr handle, JniHandleOwnership transfer) [0x0001a] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:430 
03-06 05:02:36.541 W/Xamarin.Insights(10413):   at Java.Lang.Object.GetObject[T] (IntPtr handle, JniHandleOwnership transfer) [0x00000] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:422 
03-06 05:02:36.541 W/Xamarin.Insights(10413):   at Java.Lang.Object.GetObject[T] (IntPtr jnienv, IntPtr handle, JniHandleOwnership transfer) [0x00006] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:416 
03-06 05:02:36.541 W/Xamarin.Insights(10413):   at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00000] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:80 
03-06 05:02:36.541 W/Xamarin.Insights(10413):   at (wrapper dynamic-method) System.Object:6c669bbf-ce55-4191-a207-719115cb843c (intptr,intptr)
03-06 05:02:36.651 D/Mono    (10413): DllImport searching in: '__Internal' ('(null)').
03-06 05:02:36.651 D/Mono    (10413): Searching for 'java_interop_jnienv_get_long_field'.
03-06 05:02:36.651 D/Mono    (10413): Probing 'java_interop_jnienv_get_long_field'.
03-06 05:02:36.651 D/Mono    (10413): Found as 'java_interop_jnienv_get_long_field'.
03-06 05:02:36.671 D/Mono    (10413): DllImport searching in: '__Internal' ('(null)').
03-06 05:02:36.671 D/Mono    (10413): Searching for 'java_interop_jnienv_set_int_field'.
03-06 05:02:36.671 D/Mono    (10413): Probing 'java_interop_jnienv_set_int_field'.
03-06 05:02:36.671 D/Mono    (10413): Found as 'java_interop_jnienv_set_int_field'.
03-06 05:02:36.671 D/Mono    (10413): DllImport searching in: '__Internal' ('(null)').
03-06 05:02:36.671 D/Mono    (10413): Searching for 'java_interop_jnienv_call_long_method_a'.
03-06 05:02:36.671 D/Mono    (10413): Probing 'java_interop_jnienv_call_long_method_a'.
03-06 05:02:36.671 D/Mono    (10413): Found as 'java_interop_jnienv_call_long_method_a'.
03-06 05:02:36.751 W/art     (10413): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
03-06 05:02:36.751 D/Mono    (10413): DllImport searching in: '__Internal' ('(null)').
03-06 05:02:36.751 D/Mono    (10413): Searching for 'java_interop_jnienv_throw'.
03-06 05:02:36.751 D/Mono    (10413): Probing 'java_interop_jnienv_throw'.
03-06 05:02:36.751 D/Mono    (10413): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

03-06 05:02:37.711 E/mono-rt (10413): [ERROR] FATAL UNHANDLED EXCEPTION: System.NotSupportedException: Unable to activate instance of type Java.Lang.Thread+RunnableImplementor from native handle 0xffea90dc (key_handle 0x1f522868). ---> System.MissingMethodException: No constructor found for Java.Lang.Thread+RunnableImplementor::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
03-06 05:02:37.711 E/mono-rt (10413): Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
03-06 05:02:37.711 E/mono-rt (10413): 
03-06 05:02:37.711 E/mono-rt (10413):   --- End of managed exception stack trace ---
03-06 05:02:37.711 E/mono-rt (10413): java.lang.Error: Java callstack:
03-06 05:02:37.711 E/mono-rt (10413): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
03-06 05:02:37.711 E/mono-rt (10413): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
03-06 05:02:37.711 E/mono-rt (10413): 	at android.os.Handler.handleCallback(Handler.java:739)
03-06 05:02:37.711 E/mono-rt (10413): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-06 05:02:37.711 E/mono-rt (10413): 	at android.os.Looper.loop(Looper.java:145)
03-06 05:02:37.711 E/mono-rt (10413): 	at android.app.ActivityThread.main(ActivityThread.java:6837)
03-06 05:02:37.711 E/mono-rt (10413): 	at java.lang.reflect.Method.invoke(Native Method)
03-06 05:02:37.711 E/mono-rt (10413): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-06 05:02:37.711 E/mono-rt (10413): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
03-06 05:02:37.711 E/mono-rt (10413): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
03-06 05:02:37.711 E/mono-rt (10413): 
03-06 05:02:37.711 E/mono-rt (10413):   --- End of inner exception stack trace ---
03-06 05:02:37.711 E/mono-rt (10413):   at Java.Interop.TypeManager.CreateProxy (System.Type type, IntPtr handle, JniHandleOwnership transfer) [0x00039] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Interop/TypeManager.cs:304 
03-06 05:02:37.711 E/mono-rt (10413):   at Java.Interop.TypeManager.CreateInstance (IntPtr handle, JniHandleOwnership transfer, System.Type targetType) [0x00138] in /Users/builder/data/lanes/1196/8f34ab48/source/monodroid/src/Mono.Android/src/Java.Interop/TypeManager.cs:282 
03-06 05:02:37.711 E/mono-rt (10413):   --- End of inner exception stack trace ---
03-06 05:02:37.711 E/mono-rt (10413):   at (wrapper dynamic-method) System.Object:6c669bbf-ce55-4191-a207-719115cb843c (intptr,intptr)
03-06 05:02:37.711 E/mono-rt (10413):   at (wrapper native-to-managed) System.Object:6c669bbf-ce55-4191-a207-719115cb843c (intptr,intptr)
03-06 05:02:37.721 W/Mono    (10413): The request to load the assembly System.Core v4.0.0.0 was remapped to v2.0.5.0
03-06 05:02:37.721 D/Mono    (10413): Unloading image System.Core.dll [0xf4c41100].
03-06 05:02:37.721 D/Mono    (10413): Image addref System.Core[0xd21a73a0] -> System.Core.dll[0xf4f8a000]: 10
03-06 05:02:37.731 W/Mono    (10413): The request to load the assembly System.Core v4.0.0.0 was remapped to v2.0.5.0
03-06 05:02:37.731 D/Mono    (10413): Unloading image System.Core.dll [0xf4c41100].
03-06 05:02:37.731 D/Mono    (10413): Image addref System.Core[0xd21a73a0] -> System.Core.dll[0xf4f8a000]: 11
referenceTable GDEF length=778 1
referenceTable GSUB length=6388 1
referenceTable GPOS length=66796 1
referenceTable head length=54 1
referenceTable GDEF length=778 1
referenceTable GSUB length=6384 1
referenceTable GPOS length=68718 1
referenceTable head length=54 1

```

**Comment by adrianknight89** [comment]
I can't tell if this is an issue with FFImageLoading or Xamarin Forms, but it fails my app miserably :(

**Comment by molinch** [comment]
Hi
Are you using 2.0.7.1?
There was an issue in the build 2.0.7

**Comment by daniel-luberda** [comment]
It's related to this:  http://stackoverflow.com/a/10603714/5064986

But I don't think we're missing any constructor: 

- https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Droid/Views/ImageViewAsync.cs#L13-L29
- https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Droid/Views/ManagedImageView.cs#L15-L27
- https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Forms.Droid/CachedImageView.cs#L11-L21

Any clues?

**Comment by adrianknight89** [comment]
I updated to 2.0.7.1. Same issue. As indicated before, I think this is a Xamarin issue. It's a serious one indeed. :|

https://bugzilla.xamarin.com/show_bug.cgi?id=32462
https://bugzilla.xamarin.com/show_bug.cgi?id=27408

**Comment by daniel-luberda** [comment]
@adrianknight89 As you said, we can't do anything about it. If you'll have some more info, feel free to post it here. Thanks for sharing!

**Comment by molinch** [comment]
e4381feed3b6c104ffe5afaede0e835ef00cff97 could potentially help, even though I am almost sure there is a Xamarin mystery out there

**Comment by daniel-luberda** [comment]
@molinch  I think that missing constructor is from Xamarin internal class.

**Comment by molinch** [comment]
@adrianknight89 Please reopen if it isn't coming from Xamarin

**Comment by molinch** [comment]
@adrianknight89 Have you received some news from Xamarin?

**Comment by GnanaprakashChandiran** [comment]
i am  also handle same problem... If you find any solution please post it here.

**Comment by PiMaker** [comment]
I cleaned my solution and performed a rebuild, the problem disappeared afterwards.
